stages:
  - test
  - build
  - deploy

job_test:
  stage: test
  script:
    - cd $CI_PROJECT_DIR
    - echo $CI_PROJECT_DIR
    - node -v
    - npm -v
    - npm install
    - npm run lint
    - npm run test:ci
    # - npm run e2e:ci
    - npm run build -- --aot --progress=false
    # - npm run build:prod
  cache:
    paths:
      - node_modules/
  except:
    - dev

job_build:
  stage: build
  script:
    - cd $CI_PROJECT_DIR
    - echo $CI_PROJECT_DIR
    - node -v
    - npm -v
    - npm install
    - npm run lint
    - npm run test:ci -- --coverage
    - npm run build -- --aot --progress=false
    # - npm run build:prod
  coverage: /Statements\s*:\s*([\d\.]+)%/
  artifacts:
    name: "frontend_default_build"
    paths:
      - dist/
  cache:
    paths:
      - node_modules/
  only:
    - dev

deploy_dev:
  stage: deploy
  script:
    - rm -rf /var/www/html/angular-java-dev/dist
    - cp -R dist/ /var/www/html/angular-java-dev/
    - cp -R /var/www/configs/angular-java-dev/* /var/www/html/angular-java-dev/
  environment:
    name: dev
  only:
    - dev

deploy_demo:
  stage: deploy
  script:
    - rm -rf /var/www/html/angular-java-demo/dist
    - cp -R dist/ /var/www/html/angular-java-demo/
    - cp -R /var/www/configs/angular-java-demo/* /var/www/html/angular-java-demo/
  environment:
    name: demo
  when: manual
  only:
    - dev

deploy_test_e2e:
  stage: deploy
  script:
    - rm -rf /var/www/html/angular-java-at-test-http/dist
    - cp -R dist/ /var/www/html/angular-java-at-test-http/
    - cp -R /var/www/configs/angular-java-at-test-http/* /var/www/html/angular-java-at-test-http/
  environment:
    name: e2e
  when: manual
  only:
    - dev

