stages:
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/

# job_test:
#   stage: test
#   script:
#     - cd $CI_PROJECT_DIR
#     - echo $CI_PROJECT_DIR
#     - node -v && npm -v
#     - npm install
#     - npm run lint && npm run test:ci && npm run build
#   artifacts:
#     paths:
#       - coverage
#   except:
#     - dev

pages:
  stage: test
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
    # - echo 'Welcome to GitLab Pages yo' > public/index.html
  artifacts:
    paths:
      - coverage

job_build:
  stage: build
  script:
    - cd $CI_PROJECT_DIR
    - echo $CI_PROJECT_DIR
    - node -v && npm -v && npm install
    - npm run build -- --aot --progress=false
  artifacts:
    name: "frontend_default_build"
    paths:
      - dist/
  only:
    - dev

deploy_dev:
  stage: deploy
  script:
    - rm -rf /var/www/html/angular-java-dev/dist
    - cp -R dist/ /var/www/html/angular-java-dev/
    - cp -R /var/www/configs/angular-java-dev/* /var/www/html/angular-java-dev/
  environment:
    name: dev
  only:
    - dev

deploy_demo:
  stage: deploy
  script:
    - rm -rf /var/www/html/angular-java-demo/dist
    - cp -R dist/ /var/www/html/angular-java-demo/
    - cp -R /var/www/configs/angular-java-demo/* /var/www/html/angular-java-demo/
  environment:
    name: demo
  when: manual
  only:
    - dev
