stages:
  - build
  - deploy
job_build:
  stage: build
  script:
    - cd $CI_PROJECT_DIR
    - echo $CI_PROJECT_DIR    
    - npm install
    - npm run build -- --prod --aot --progress=false
  artifacts:
    name: "frontend_default_build"
    paths:
      - dist/
  only:
    - dev

deploy_dev:
  stage: deploy
  script:
    - rm -rf /var/www/html/angular-java-dev/dist
    - cp -R dist/ /var/www/html/angular-java-dev/
    - cp -R /var/www/configs/angular-java-dist/* /var/www/html/angular-java-dev/
  environment:
    name: dev    
  only:
    - dev