import { Injectable } from '@angular/core';

@Injectable()
export class LookupService {
  static LOOKUP_ROLES_FETCH         = 'LOOKUP_ROLES_FETCH';
  static LOOKUP_ROLES_FETCH_SUCCESS = 'LOOKUP_ROLES_FETCH_SUCCESS';
  static LOOKUP_ROLES_FETCH_FAILURE = 'LOOKUP_ROLES_FETCH_FAILURE';
  static LOOKUP_USERS_FETCH         = 'LOOKUP_USERS_FETCH';
  static LOOKUP_USERS_FETCH_SUCCESS = 'LOOKUP_USERS_FETCH_SUCCESS';
  static LOOKUP_USERS_FETCH_FAILURE = 'LOOKUP_USERS_FETCH_FAILURE';
}
