import { Component } from '@angular/core';

@Component({
  selector: 'app-layout',
  templateUrl: './layout.component.html',
  styleUrls: ['./layout.component.scss']
})
export class LayoutComponent {
  titles = {
    ActionsLogComponent: 'ACTIONS_LOG',
    CallCenterComponent: 'CALL_CENTER',
    CampaignComponent: 'CALL_CENTER',
    CampaignsComponent: 'CAMPAIGNS',
    ConstantsComponent: 'CONSTANTS',
    ContactLogComponent: 'CONTACT_LOG',
    ContactRegistrationComponent: 'CONTACT_REGISTRATION',
    ContactPropertiesComponent: 'CONTACT_TREES',
    ContractorsAndPortfoliosComponent: 'PORTFOLIOS_CONTRACTORS',
    ContractorAttributesComponent: 'CONTRACTOR_ATTRIBUTES',
    ContractorEditComponent: 'CONTRACTOR',
    ContractorManagersComponent: 'CONTRACTOR_MANAGERS',
    ContractorManagerEditComponent: 'CONTRACTOR_MANAGER',
    DashboardComponent: 'HOME',
    DataUploadComponent: 'DATA_UPLOAD',
    DebtorComponent: 'DEBTOR_CARD',
    DebtorActionLogComponent: 'DEBTOR_ACTION_LOG',
    DebtorAddressComponent: 'DEBTOR_ADDRESS',
    DebtorContactsComponent: 'DEBTOR_DEBT_CONTACTS',
    DebtorContactLogTabComponent: 'DEBTOR_CONTACT_LOG_COMPONENT',
    DebtorDebtComponent: 'DEBTOR_DEBT',
    DebtorDebtComponentComponent: 'DEBTOR_DEBT_COMPONENT',
    DebtorDocumentComponent: 'DEBTOR_DOCUMENT',
    DebtorEmailComponent: 'DEBTOR_EMAIL',
    DebtorEmploymentComponent: 'DEBTOR_EMPLOYMENT',
    DebtorGuarantorComponent: 'DEBTOR_GUARANTEE',
    DebtorIdentityComponent: 'DEBTOR_IDENTITY',
    DebtorPaymentComponent: 'DEBTOR_PAYMENT',
    DebtorPhoneComponent: 'DEBTOR_PHONE',
    DebtorPromiseComponent: 'DEBTOR_PROMISE',
    DebtorPropertyComponent: 'DEBTOR_PROPERTY',
    DebtorPledgeComponent: 'DEBTOR_PLEDGE',
    DebtorsComponent: 'DEBT_LIST',
    DebtProcessingComponent: 'DEBTS',
    DictionariesComponent: 'DICTIONARIES',
    HelpComponent: 'HELP',
    IncomingCallComponent: 'INCOMING_CALL',
    MessageTemplatesComponent: 'MESSAGE_SCENARIOS',
    OrganizationsComponent: 'DEPARTMENTS',
    PaymentsComponent: 'PAYMENTS',
    PaymentsUploadComponent: 'UPLOAD_TEMPLATES',
    PortfolioAttributesComponent: 'PORTFOLIO_ATTRIBUTES',
    PortfolioEditComponent: 'PORTFOLIO_EDIT',
    RolesAndPermissionsComponent: 'ROLES_AND_PERMISSIONS',
    UsersComponent: 'USERS',
    UserEditComponent: 'USER_EDIT',
    WorkTaskComponent: 'WORK_TASK',
  };

  constructor() {}
}
